# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:

  - stage: Deploy_Dev

    displayName: "Deploy APIM to Dev Environment" 
    variables:
      - group: ExternalVars-Dev

    jobs:
      
    - job : "Deploy_Dev"
      displayName: "Deploy APIM to Dev Environment"
      pool:
        vmImage: ubuntu-latest
      steps:

      - task: AzureCLI@2
        displayName: 'Deploy APIM ' 
        inputs:
          azureSubscription: $(serviceconnectionname)
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |    
            echo 'Deploy APIM Service'                  
            az deployment group create --name DeployAPIM --resource-group $(resourceGroupName) --template-file './example/service.template.json' --mode 'Incremental' --parameters publisherEmail=$(publisherEmail) ApimServiceName=$(ApimServiceName) publisherName=$(publisherName)

            echo 'Deploy APIM Groups'
            az deployment group create --name DeployAPIM --resource-group $(resourceGroupName) --template-file './example/groups.template.json' --mode 'Incremental' --parameters ApimServiceName=$(ApimServiceName)

            echo 'Deploy APIM Starter product'
            az deployment group create --name DeployAPIM --resource-group $(resourceGroupName) --template-file './example/products/product-starter.template.json' --mode 'Incremental' --parameters ApimServiceName=$(ApimServiceName)

            echo 'Deploy APIM Unlimited product'
            az deployment group create --name DeployAPIM --resource-group $(resourceGroupName) --template-file './example/products/product-unlimited.template.json' --mode 'Incremental' --parameters ApimServiceName=$(ApimServiceName)

            echo 'Deploy API httpbin version set base'
            az deployment group create --name DeployAPIM --resource-group $(resourceGroupName) --template-file './example/api-httpbin/api-httpbin.version-set.template.json' --parameters ApimServiceName=$(ApimServiceName)

            echo 'Deploy API httpbin v1'
            az deployment group create --name DeployAPIM --resource-group $(resourceGroupName) --template-file './example/api-httpbin/v1/api-httpbin.v1.template.json' --parameters ApimServiceName=$(ApimServiceName)

            echo 'Deploy API httpbin v2'
            az deployment group create --name DeployAPIM --resource-group $(resourceGroupName) --template-file './example/api-httpbin/v2/api-httpbin.v2.template.json' --parameters ApimServiceName=$(ApimServiceName)

            echo 'Deploy API httpbin v2-rev2'
            az deployment group create --name DeployAPIM --resource-group $(resourceGroupName) --template-file './example/api-httpbin/v2-rev2/api-httpbin.v2-rev2.template.json' --parameters ApimServiceName=$(ApimServiceName)

            echo 'Deploy API httpbin v2-switch-rev'
            az deployment group create --name DeployAPIM --resource-group $(resourceGroupName) --template-file './example/api-httpbin/v2-switch-rev/api-httpbin.v2.switch.template.json' --parameters ApimServiceName=$(ApimServiceName)

  - stage: Deploy_Prod

    displayName: "Deploy APIM to Production Environment" 
    variables:
      - group: ExternalVars-Prod

    jobs:
      
    - job : "Deploy_Prod"
      displayName: "Deploy APIM to Prod Environment"
      pool:
        vmImage: ubuntu-latest
      steps:

        
      - task: AzureCLI@2
        displayName: 'Deploy APIM Service'
        inputs:
          azureSubscription: $(serviceconnectionname)
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |    
            echo 'Deploy APIM Service'                  
            az deployment group create --name DeployAPIM --resource-group $(resourceGroupName) --template-file './example/service.template.json' --mode 'Incremental' --parameters publisherEmail=$(publisherEmail) ApimServiceName=$(ApimServiceName) publisherName=$(publisherName)

            echo 'Deploy APIM Groups'
            az deployment group create --name DeployAPIM --resource-group $(resourceGroupName) --template-file './example/groups.template.json' --mode 'Incremental' --parameters ApimServiceName=$(ApimServiceName)

            echo 'Deploy APIM Starter product'
            az deployment group create --name DeployAPIM --resource-group $(resourceGroupName) --template-file './example/products/product-starter.template.json' --mode 'Incremental' --parameters ApimServiceName=$(ApimServiceName)

            echo 'Deploy APIM Unlimited product'
            az deployment group create --name DeployAPIM --resource-group $(resourceGroupName) --template-file './example/products/product-unlimited.template.json' --mode 'Incremental' --parameters ApimServiceName=$(ApimServiceName)

            echo 'Deploy APIM Unlimited product'
            az deployment group create --name DeployAPIM --resource-group $(resourceGroupName) --template-file './example/products/product-unlimited.template.json' --mode 'Incremental' --parameters ApimServiceName=$(ApimServiceName)

            echo 'Deploy httpbin Version Set to prod'
            az deployment group create --name DeployAPIM --resource-group $(resourceGroupName) --template-file './APIs/httpBinAPI/contosobob-prod-apiVersionSets.template.json' --mode 'Incremental' --parameters ApimServiceName=$(ApimServiceName)

            echo 'Create Or Update Resource Global Group '
            az deployment group create --name DeployAPIM --resource-group $(resourceGroupName) --template-file './APIs/httpBinAPI/contosobob-prod-globalServicePolicy.template.json' --mode 'Incremental' --parameters ApimServiceName=$(ApimServiceName)

            echo 'Deploy Products to prod for HttpBin'
            az deployment group create --name DeployAPIM --resource-group $(resourceGroupName) --template-file './APIs/httpBinAPI/contosobob-prod-products.template.json' --mode 'Incremental' --parameters ApimServiceName=$(ApimServiceName)

            echo 'Deploy API HttpBin to prod for HttpBin'
            az deployment group create --name DeployAPIM --resource-group $(resourceGroupName) --template-file './APIs/httpBinAPI/contosobob-prod-httpBinAPI-api.template.json' --mode 'Incremental' --parameters ApimServiceName=$(ApimServiceName)

            echo 'Create Or Update Resource Group for HttpBin'
            az deployment group create --name DeployAPIM --resource-group $(resourceGroupName) --template-file './APIs/httpBinAPI/contosobob-prod-productAPIs.template.json' --mode 'Incremental' --parameters ApimServiceName=$(ApimServiceName)
