blank_issues_enabled: true
contact_links:
  - name: Ask a question 💬
    url: https://github.com/Azure/azure-api-management-devops-resource-kit/discussions
    about: Ask a question or request support for using Azure API Management DevOps Resource Kit.
  - name: Feature request for Azure API Management 🔭
    url: http://aka.ms/apimwish
    about: Suggest an idea for Azure API Management in general