authenticationSettings:
    subscriptionKeyRequired: false
    openid: 
        openidProviderId: serverId
        bearerTokenSendingMethods:
          - authorizationHeader 
          - query
    oAuth2:
        authorizationServerId: serverId
        scope: scope
      