jobs:
- job: Build
  pool:
    vmImage: 'VSEngSS-MicroBuild2022-1ES'
  
  steps:
  - template: common/build-and-test.yml

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  always: true # Run even when there are no code changes
  branches:
    include:
    - main

# no PR triggers
pr: none